### ISSUE TITLE
Quickened condition causes error to other uses while moving while using this module

### ISSUE THREAD

**Issue by fraserstanton** [velara/pf2edragruler#15] opened 2021-05-30 03:30 UTC
![image](https://user-images.githubusercontent.com/85046656/120091059-3cb7df80-c0bc-11eb-9f88-d034b7b6cffd.png)
While a quickened player (player with quickened condition) moves around all the other players (not GM) get an error (_User xxx lacks permission to update Actor yyyyyyyy_, as can be seen in the screen shot.)
I have the following drag ruler related modules loaded:
Drag Ruler
Enhanced Terrain Layer
PF2E Drag Ruler Integration
If I turned off PF2E Drag Ruler Integration, the error no longer happened. We also tested a bunch of other conditions and none caused the issue.

**Comment by velara** [comment] 2021-05-30 14:14
What version of Drag Ruler/Drag Ruler Integration are you running? If it isn’t v0.4.6 updating might fix your problem as a bug that caused a similar error was present in one of the older releases.

Do you have Partial Move actions enabled in the settings? Try turning it off, it was the cause of the original permission bug that was reported. I couldn’t reproduce it so I tried to fix it blind and it’s possible this is a lingering part of that set of issues.

Neither of the above help fix your problem, let me know. Since then I’ll be in uncharted territory.

Otherwise your report will be super useful for helping resolve the permission bug.

**Comment by fraserstanton** [comment] 2021-05-30 23:08
Everything is updated to the most recent as of yesterday.
Drag Ruler 1.7.2, Enhanced Terrain Layer 1.0.27, PF2E Drag Ruler Integration 0.4.6
Partial Move is not enabled.
I am happy to allow you to log on to my game and reproduce the bug for you.
Thanks for the follow up.

**Comment by velara** [comment] 2021-05-31 19:53
I appreciate the offer. But I might have difficulty finding a good time to be able to hop onto your game to the see the issue.  I'll see if I can track it down based on the information that you're reported. And if not I'll get in touch to try and get more info/see if I can find a feasible time.

**Comment by velara** [comment] 2021-06-01 19:28
I managed to replicate it. And it should be fixed in version 0.4.7

**Closed as completed by velara** 2021-06-01 19:28 UTC

**Comment by fraserstanton** [comment] 2021-06-02 01:59
Tested it, it works. Thanks.
