### ISSUE TITLE
Error spam when walking with token

### ISSUE THREAD

**Issue by Nelzy** [velara/pf2edragruler#22] opened 2021-08-17 00:04 UTC
Anytime move a token with Movement Effect "ignore non-magical" effect this error message(attach a image) is spammed in the console.

ReferenceError: TerrainList is not defined
   at evnReductions (bundle.js:255)
   at PF2ESpeedProvider.getCostForStep (bundle.js:106)
   at getCostFromSpeedProvider (api.js:111)
   at opts.costFunction (compatability.js:28)
   at measure.js:112
   at Array.map (<anonumous>)
   at measureDistanceSquare (measure.js:32)
   at Object.measureDistances (measure.js:19)
   at measureDistances (compatibility.js:31)
   at DragrulerRuler.measure (foundry imports.js:212)
![error](https://user-images.githubusercontent.com/1939467/129641928-32b02fd4-ea6a-4929-a5e3-b58dfd2dfb94.png)

Foundry 0.8.8
Pathfinder 2nd Edition 2.11.1.7257

My full mod list is:
Coursor Hider
Drag Ruler
Enhanced Terrain Layer
Health Estimate
llibWrapper
Multilevel Tokens
Pathfinder 2e Quick Rolls
PF2E Drag Ruler Integration
PF2E Loot Generator
PF2E Persistent Damage
PF2E Toolbox
PopOut!
Settings Extender
socketlib
Terrain Ruler
Token Action HUD
Universal Battlemap importer
Wall Height

Tested with only this list just to be sure, but the same error happens
Drag Ruler
Enhanced Terrain Layer
PF2E Drag Ruler Integration
socketlib
Terrain Ruler

**Comment by velara** [comment] 2021-08-27 18:09
This was caused by a type introduced during refactoring. I've got a fix pending, but there are other issues with non-magical terrain that need to be resolved before I release the fix.

**Comment by velara** [comment] 2021-08-29 21:21
Closed in V0.5.3

**Closed as completed by velara** 2021-08-29 21:21 UTC
